
# minio 连接相关
app:
  # 流程相关
  flow:
    # 流程根目录
    folder-flow: V:\flow_temp\temp
    # 流程运行控制台日志
    log-console: false

  # 控制上传过程
  service-upload:
    enable: true

  service-merge:
    enable: true
    filename-merge: file_merge.bin

  # 控制转码切片过程
  service-transcode:
    ffmpeg-base:
      enable: true
      path-ffmpeg: ffmpeg
      path-ffprobe: ffprobe
    ffmpeg-m3u8:
      enable: true
      folder-transcode-m3u8: ./m3u8

  # 控制存储过程
  service-storage:
    file-system:
      enable: true
      # 文件系统的储存位置
      folder-storage: V:\flow_temp\storage
    minio:
      enable: true
      url: http://192.168.19.115:29001
      username: minio-server
      password: minio-server-password-000*
    qiniu:
      enable: true
      access-key: K4AyEBRYQYDTY5Gx7BPIsQQib1aIE4MwXD7b83_P
      secret-key: lllhjhaQtIvXJXBo540Miw2VZzqT9Olf1o48kx6N
      # 为什么这么写捏 因为找了半天都没跑通注入实体的办法
      buckets: '{"firok-test-public":{"region":"huadong","domain":"rc3wj1b5q.hd-bkt.clouddn.com","use-https":false,"deadline":36000},"demo-firok":{"region":"huadong","domain":"rb2uaos6l.hd-bkt.clouddn.com","use-https":false,"deadline":36000}}'

server:
  port: 29011
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.80.167:3306/sdyzt?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
#    username: root
#    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jfb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: HikariCorePool
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select * from information_schema.tables limit 1
    initialization-mode: always
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB

mybatis-plus:

