
# minio 连接相关
app:
  # 流程相关
  flow:
    # 流程根目录
    folder-flow: ./cache
    # 流程运行控制台日志
    log-console: false

  # 控制上传过程
  service-upload:
    enable: true
    folder-cache: ./cache

  # 控制转码切片过程
  service-transcode:
    ffmpeg-base:
      enable: true
      path-ffmpeg: ./ffmpeg
      path-ffprobe: ./ffprobe
    ffmpeg-m3u8:
      enable: true

  # 控制存储过程
  service-storage:
    file-system:
      enable: true
      # 文件系统的储存位置
      folder-storage: ./storage
    minio:
      enable: true
      url: http://192.168.19.115:29001
      username: minio-server
      password: minio-server-password-000*
    qiniu:
      enable: true
      access-key: K4AyEBRYQYDTY5Gx7BPIsQQib1aIE4MwXD7b83_P
      secret-key: lllhjhaQtIvXJXBo540Miw2VZzqT9Olf1o48kx6N
      region: huadong
      domain: "rb2uaos6l.hd-bkt.clouddn.com"
      use-https: false
      deadline: 3600

  minio:
    # minio 地址
    url: http://192.168.19.115:29001
    username: minio-server
    password: minio-server-password-000*
    name-bucket: jfb
  cache:
    # 缓存文件夹 用于储存各种切片文件/转码文件
    folder: ./cache
  lib:
    # 如果没有提供, 则自动从资源文件导出出一份能用的库文件到lib目录
    # 很可能这个最终只会面向windows系统进行操作
    # ffmpeg 可执行文件路径
    ffmpeg: ffmpeg
    # ffprobe 可执行文件路径
    ffprobe: ffprobe

server:
  port: 29011
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.80.167:3306/sdyzt?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
#    username: root
#    password: root
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.80.103:5432/chengyang?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: postgres
    password: postgres
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: HikariCorePool
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select * from information_schema.tables limit 1
    initialization-mode: always
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
